### ISSUE TITLE
Changing linter rule react-hooks/exhaustive-deps from 'error' to 'warn'

### ISSUE THREAD

**Issue by Maren-Osnabrug** [storyofams/eslint-config-ams#2]
**I'm always frustrated when** I have to pass a method to useEffect, when I want to run that method only on mount

**Describe the solution you'd like** changing the rule react-hooks/exhaustive-deps from 'error' to 'warn'. 

**Describe alternatives you've considered** //eslint-disable-next-line react-hooks/exhaustive-deps

**Additional context** 
The way the rule is set up now, prevents the valid case of using an empty deps array to run on mount and has the developers adding extra dependencies in the form of methods. These methods then have to be wrapped in useCallback, to prevent extra rendering loops. The extra code is unneccesary but introduces more lines of code.

https://github.com/storyofams/eslint-config-ams/blob/91f1317f41714c2178ba204e09c07fdb4ba6465a/.eslintrc.js#L226

**Comment by BJvdA** [comment]
I was considering turning it off completely
